CREATE TABLE IF NOT EXISTS category (
  id  SERIAL PRIMARY KEY,
  body JSONB,
  insert_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_update_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_category_body ON category USING GIN (body);
GRANT SELECT, INSERT, UPDATE, DELETE ON category TO ourroots;
GRANT USAGE, SELECT on SEQUENCE category_id_seq to ourroots;