version: "3.0"
services:
  postgres:
    container_name: cms-test_postgres
    image: postgres:10.7
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
