version: "3.0"
services:
  postgres:
    image: postgres:10.7
    ports:
      - "5432:5432"
    volumes:
      - cms_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ourroots
    networks:
      - mynetwork
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - BASE_URL=http://localhost:8000
      - PERSISTER=sql
      - DATABASE_URL=postgres://ourroots:password@postgres:5432/cms?sslmode=disable
    networks:
      - mynetwork
volumes:
  cms_pgdata:
    external: true
networks:
  mynetwork:
    driver: bridge
