version: "3.0"
services:
  postgres:
    image: postgres:10.7
    ports:
      - "5432:5432"
    volumes:
      - cms_pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ourroots
    networks:
      - mynetwork

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - cms_s3data:/data
    environment:
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
    command: server /data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork

  recordswriter:
    build:
      context: .
      dockerfile: Dockerfile.recordswriter
    image: recordswriter
    depends_on:
      - postgres
      - minio
      - rabbitmq
    environment:
      - BASE_URL=http://localhost:8000
      - DATABASE_URL=postgres://ourroots:password@postgres:5432/cms?sslmode=disable
      - AWS_REGION=us-east-1
      - BLOB_STORE_BUCKET=cmsbucket
      # this configures minio; to use S3, omit these settings and set the bucket to a bucket you own
      - BLOB_STORE_ENDPOINT=127.0.0.1:9000
      - BLOB_STORE_ACCESS_KEY=minioaccess
      - BLOB_STORE_SECRET_KEY=miniosecret
      - BLOB_STORE_DISABLE_SSL=true
      # this configures rabbitmq; to use SQS, set the protocol to awssqs and the host to sqs.us-east-1.amazonaws.com/<accountid>
      - PUB_SUB_PROTOCOL=rabbit
      - PUB_SUB_HOST=guest:guest@rabbitmq:5672
    networks:
      - mynetwork

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - BASE_URL=http://localhost:8000
      - DATABASE_URL=postgres://ourroots:password@postgres:5432/cms?sslmode=disable
      - AWS_REGION=us-east-1
      - BLOB_STORE_BUCKET=cmsbucket
      # this configures minio; to use S3, omit these settings and set the bucket to a bucket you own
      - BLOB_STORE_ENDPOINT=127.0.0.1:9000
      - BLOB_STORE_ACCESS_KEY=minioaccess
      - BLOB_STORE_SECRET_KEY=miniosecret
      - BLOB_STORE_DISABLE_SSL=true
      # this configures rabbitmq; to use SQS, set the protocol to awssqs and the host to sqs.us-east-1.amazonaws.com/<accountid>
      - PUB_SUB_PROTOCOL=rabbit
      - PUB_SUB_HOST=guest:guest@rabbitmq:5672
      - OIDC_DOMAIN=ourroots.auth0.com
      - OIDC_AUDIENCE=https://api.ourroots.org/preprod
    networks:
      - mynetwork

volumes:
  cms_pgdata:
    external: true
  cms_s3data:
    external: true

networks:
  mynetwork:
    driver: bridge
