version: "3.0"
services:
  postgres_test:
    image: postgres:10.7
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork_test

  minio_test:
    image: minio/minio
    ports:
      - "19000:9000"
    environment:
      MINIO_ACCESS_KEY: minioaccess
      MINIO_SECRET_KEY: miniosecret
    entrypoint: sh
    command: -c 'mkdir -p /data/testbucket && /usr/bin/minio server /data'
    networks:
      - mynetwork_test

  rabbitmq_test:
    image: rabbitmq:3-management-alpine
    ports:
      - "25672:5672"
      - "35672:15672"
    volumes:
      - ./rabbitmq_advanced.config:/etc/rabbitmq/advanced.config
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mynetwork_test

networks:
  mynetwork_test:
    driver: bridge
