version: "3.0"
services:
  postgres:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
