basePath: /
definitions:
  model.Category:
    properties:
      csv_heading:
        type: string
      field_defs:
        $ref: '#/definitions/model.FieldDefSet'
        description: swaggertype:"map[string]string" example:"{\"int_field\":\"Int\",
          \"string_field\":\"String\"}"
      id:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  model.CategoryInput:
    properties:
      csv_heading:
        type: string
      field_defs:
        $ref: '#/definitions/model.FieldDefSet'
        description: swaggertype:"map[string]string" example:"{\"int_field\":\"Int\",
          \"string_field\":\"String\"}"
      name:
        type: string
    type: object
  model.Collection:
    properties:
      category:
        $ref: '#/definitions/model.Category'
      id:
        type: string
      location:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  model.CollectionInput:
    properties:
      category:
        $ref: '#/definitions/model.Category'
      location:
        type: string
      name:
        type: string
    type: object
  model.Error:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.FieldDefSet:
    additionalProperties:
      type: string
    type: object
host: api.ourroots.org
info:
  contact:
    email: jim@anconafamily.com
    name: Jim Ancona
    url: https://github.com/jancona
  description: This is the OurRoots API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OurRoots API
  version: 0.1.0
paths:
  /categories:
    get:
      operationId: getCategories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: returns all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      operationId: addCategory
      parameters:
      - description: Add Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.CategoryInput'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: adds a new Category
      tags:
      - categories
  /categories/{id}:
    delete:
      operationId: deleteCategory
      parameters:
      - description: Category ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: deletes a Category
      tags:
      - categories
    get:
      operationId: getCategory
      parameters:
      - description: Category ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: gets a Category
      tags:
      - categories
    patch:
      consumes:
      - application/json
      operationId: updateCategory
      parameters:
      - description: Category ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Update Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.CategoryInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: updates a Category
      tags:
      - categories
  /collections:
    get:
      operationId: getCollections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Collection'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: returns all collections
      tags:
      - collections
    post:
      consumes:
      - application/json
      operationId: addCollection
      parameters:
      - description: Add Collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/model.CollectionInput'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: adds a new Collection
      tags:
      - collections
  /collections/{id}:
    delete:
      operationId: deleteCollection
      parameters:
      - description: Collection ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: deletes a Collection
      tags:
      - collections
    get:
      operationId: getCollection
      parameters:
      - description: Collection ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: gets a Collection
      tags:
      - collections
    patch:
      consumes:
      - application/json
      operationId: updateCollection
      parameters:
      - description: Collection ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: Update Collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/model.CollectionInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: updates a Collection
      tags:
      - collections
schemes:
- http
- https
swagger: "2.0"
