basePath: /
definitions:
  model.Category:
    properties:
      field_defs:
        $ref: '#/definitions/model.FieldDefSet'
        description: example:"{\"int_field\":\"Int\", \"string_field\":\"String\"}"
        type: object
      id:
        example: /categories/999
        type: string
      insert_time:
        type: string
      last_update_time:
        type: string
      name:
        type: string
    required:
    - id
    - name
    type: object
  model.CategoryIn:
    properties:
      field_defs:
        $ref: '#/definitions/model.FieldDefSet'
        description: example:"{\"int_field\":\"Int\", \"string_field\":\"String\"}"
        type: object
      name:
        type: string
    required:
    - name
    type: object
  model.Collection:
    properties:
      category:
        example: /categories/999
        type: string
      citation_template:
        type: string
      id:
        example: /collections/999
        type: string
      insert_time:
        type: string
      last_update_time:
        type: string
      location:
        type: string
      name:
        type: string
    required:
    - category
    - id
    - name
    type: object
  model.CollectionIn:
    properties:
      category:
        example: /categories/999
        type: string
      citation_template:
        type: string
      location:
        type: string
      name:
        type: string
    required:
    - category
    - name
    type: object
  model.Errors:
    type: object
  model.FieldDef:
    properties:
      csv_heading:
        type: string
      name:
        type: string
      type:
        enum:
        - Int
        - String
        - Image
        - Location
        - Time
        type: string
    type: object
  model.FieldDefSet:
    items:
      $ref: '#/definitions/model.FieldDef'
    type: array
host: api.ourroots.org
info:
  contact:
    email: jim@anconafamily.com
    name: Jim Ancona
    url: https://github.com/jancona
  description: This is the OurRoots API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OurRoots API
  version: 0.1.0
paths:
  /categories:
    get:
      operationId: getCategories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: returns all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      operationId: addCategory
      parameters:
      - description: Add Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.CategoryIn'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: adds a new Category
      tags:
      - categories
  /categories/{id}:
    delete:
      operationId: deleteCategory
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: OK
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: deletes a Category
      tags:
      - categories
    get:
      operationId: getCategory
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: gets a Category
      tags:
      - categories
    put:
      consumes:
      - application/json
      operationId: updateCategory
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Category
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: updates a Category
      tags:
      - categories
  /collections:
    get:
      operationId: getCollections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Collection'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: returns all collections
      tags:
      - collections
    post:
      consumes:
      - application/json
      operationId: addCollection
      parameters:
      - description: Add Collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/model.CollectionIn'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: adds a new Collection
      tags:
      - collections
  /collections/{id}:
    delete:
      operationId: deleteCollection
      parameters:
      - description: Collection ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: deletes a Collection
      tags:
      - collections
    get:
      operationId: getCollection
      parameters:
      - description: Collection ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: gets a Collection
      tags:
      - collections
    put:
      consumes:
      - application/json
      operationId: updateCollection
      parameters:
      - description: Collection ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update Collection
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/model.Collection'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Collection'
        "415":
          description: Bad Content-Type
          schema:
            $ref: '#/definitions/model.Errors'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/model.Errors'
      summary: updates a Collection
      tags:
      - collections
schemes:
- http
- https
swagger: "2.0"
